# Generated by Django 2.0.2 on 2020-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.FloatField()),
                ('outstanding_amt', models.FloatField()),
                ('maturity_day', models.FloatField()),
                ('monthly_installment', models.FloatField()),
                ('contract_status', models.CharField(choices=[('1,0,0,0', 'Option-1'), ('0,1,0,0', 'Option-2'), ('0,0,1,0', 'Option-3'), ('0,0,0,1', 'Option-4')], max_length=10)),
                ('term_status', models.CharField(choices=[('1,0', 'Option-1'), ('0,1', 'Option-2')], max_length=10)),
            ],
        ),
    ]
