# Generated by Django 3.0.2 on 2020-01-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='term_status',
            field=models.CharField(choices=[('1,0', 'Short-Term'), ('0,1', 'Long-Term')], max_length=10),
        ),
    ]
